# Generated by Django 5.2.9 on 2025-12-12 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='type',
            field=models.CharField(choices=[('learnership', 'Learnership'), ('internship', 'Internship')], default='learnership', max_length=20),
        ),
    ]
