# Generated by Django 5.2.9 on 2025-12-12 11:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='description',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='tagline',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='website',
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='company_profile/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
