# Generated by Django 5.2.9 on 2025-12-12 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('program', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField(blank=True)),
                ('cv', models.FileField(blank=True, null=True, upload_to='applications/cv/')),
                ('id_document', models.FileField(blank=True, null=True, upload_to='applications/ids/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
